# Generated by Django 4.0.1 on 2022-01-23 11:51

import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Listings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('seller_name', models.CharField(max_length=30)),
                ('contact_number', models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('make', models.CharField(max_length=20)),
                ('model', models.CharField(max_length=30)),
                ('year', models.PositiveIntegerField(default=2022, validators=[django.core.validators.MinValueValidator(1886), django.core.validators.MaxValueValidator(2022)])),
                ('condition', models.CharField(choices=[('poor', 'Poor'), ('fair', 'Fair'), ('good', 'Good'), ('excellent', 'Excellent')], default='poor', max_length=9)),
                ('price', models.IntegerField(validators=[django.core.validators.MinValueValidator(1000), django.core.validators.MaxValueValidator(100000)])),
            ],
        ),
    ]
