# Generated by Django 4.0.1 on 2022-01-23 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0002_listings_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='listings',
            name='image',
            field=models.ImageField(default=None, upload_to='uploads/'),
            preserve_default=False,
        ),
    ]
