# Generated by Django 4.0.1 on 2022-01-23 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0003_listings_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listings',
            name='image',
        ),
    ]
