# Generated by Django 4.0.1 on 2022-01-23 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0004_remove_listings_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='listings',
            name='sold',
            field=models.BooleanField(default=False),
        ),
    ]
