# Generated by Django 4.0.1 on 2022-01-23 16:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0006_interest'),
    ]

    operations = [
        migrations.AddField(
            model_name='interest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='interest',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('in_process', 'In Process'), ('closed', 'Close')], default='poor', max_length=15),
        ),
    ]
