# Generated by Django 4.0.1 on 2022-01-23 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0007_interest_created_at_interest_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='interest',
            name='listing',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='listing.listings'),
            preserve_default=False,
        ),
    ]
