# Generated by Django 4.0.1 on 2022-01-23 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0009_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
