# Generated by Django 4.0.1 on 2022-01-24 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0013_alter_listings_contact_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interest',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('in_process', 'In Process'), ('closed', 'Close')], default='open', max_length=15),
        ),
    ]
